import turtle

scr=turtle.Screen()
scr.title("Rainbow colors")
scr.setup(1000,700)

# circle
pen=turtle.Turtle()
pen.shape("turtle")
pen.color("violet")
pen.pensize(25)
pen.circle(100)

pen=turtle.Turtle()
pen.shape("turtle")
pen.color("indigo")
pen.pensize(25)
pen.penup()
pen.goto(0,-20)
pen.down()
pen.circle(120)

pen=turtle.Turtle()
pen.shape("turtle")
pen.color("blue")
pen.pensize(25)
pen.penup()
pen.goto(0,-40)
pen.down()
pen.circle(140)

pen=turtle.Turtle()
pen.shape("turtle")
pen.color("green")
pen.pensize(25)
pen.penup()
pen.goto(0,-60)
pen.down()
pen.circle(160)

pen=turtle.Turtle()
pen.shape("turtle")
pen.color("yellow")
pen.pensize(25)
pen.penup()
pen.goto(0,-80)
pen.down()
pen.circle(180)

pen=turtle.Turtle()
pen.shape("turtle")
pen.color("orange")
pen.pensize(25)
pen.penup()
pen.goto(0,-100)
pen.down()
pen.circle(200)

pen=turtle.Turtle()
pen.shape("turtle")
pen.color("red")
pen.pensize(25)
pen.penup()
pen.goto(0,-120)
pen.down()
pen.circle(220)

#square
sq=turtle.Turtle()
sq.shape("turtle")
sq.color("white")
sq.pensize(10)
sq.penup()
sq.goto(-250,80)
sq.pendown()
sq.fillcolor("white")
sq.begin_fill()
for i in range(4):
    sq.forward(500)
    sq.right(90)
sq.end_fill()
sq.hideturtle()

